# Generated by Django 4.2.5 on 2023-10-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_code', models.CharField()),
                ('event_name', models.CharField(max_length=255)),
                ('event_data', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Faculty_Advisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_code', models.CharField()),
                ('name', models.CharField()),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Faculty_Advisors',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Organisation Users',
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_advisor', models.CharField()),
                ('organisation_code', models.CharField()),
                ('event_name', models.CharField()),
                ('participant_email', models.CharField()),
                ('status', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Certificates',
                'unique_together': {('organisation_code', 'event_name', 'participant_email')},
            },
        ),
    ]
