# Generated by Django 4.2.5 on 2023-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users_date_joined_users_groups_users_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_org',
            field=models.BooleanField(default=False),
        ),
    ]
