# Generated by Django 4.2.5 on 2023-10-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_events_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='organisation',
            new_name='organisation_code',
        ),
        migrations.AlterUniqueTogether(
            name='events',
            unique_together={('organisation_code', 'event_name')},
        ),
    ]
