# Generated by Django 4.2.5 on 2023-10-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_organisation_events_organisation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
    ]
