# Generated by Django 4.2.5 on 2023-10-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_events_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Advisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_code', models.CharField()),
                ('name', models.CharField()),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Faculty_Advisors',
            },
        ),
    ]
