# Generated by Django 4.2.5 on 2023-10-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
