# Generated by Django 4.2.5 on 2023-10-08 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_users_delete_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='events',
            unique_together=set(),
        ),
    ]
