# Generated by Django 4.2.5 on 2023-10-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_users_managers_remove_users_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='organisation_code',
            new_name='organisation',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_data',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(unique=True),
        ),
    ]
