# Generated by Django 4.2.5 on 2023-10-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_events_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
