# Generated by Django 4.2.5 on 2023-10-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_organisation_code_events_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_data',
            field=models.FileField(upload_to='events/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>/'),
        ),
    ]
