# Generated by Django 4.2.5 on 2023-10-18 15:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_events_event_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_data',
            field=models.FileField(upload_to=main.models.event_data_upload_path),
        ),
    ]
