# Generated by Django 4.2.5 on 2023-10-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_users_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_code', models.CharField()),
                ('event_name', models.CharField()),
                ('email', models.CharField()),
                ('status', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Certificates',
                'unique_together': {('organisation_code', 'event_name', 'email')},
            },
        ),
    ]
