# Generated by Django 4.2.5 on 2023-10-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_certificates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='email',
            new_name='participant_email',
        ),
        migrations.AlterUniqueTogether(
            name='certificates',
            unique_together={('organisation_code', 'event_name', 'participant_email')},
        ),
    ]
