# Generated by Django 4.2.5 on 2023-10-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_email_certificates_participant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
