# Generated by Django 4.2.5 on 2023-10-19 04:05

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_events_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='certificate',
            field=models.FileField(default='null', upload_to=main.models.certificate_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='coordinates',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
