# Generated by Django 4.2.5 on 2023-10-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_events_certificate_events_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_advisors',
            old_name='name',
            new_name='organisation',
        ),
        migrations.AlterField(
            model_name='faculty_advisors',
            name='email',
            field=models.CharField(),
        ),
        migrations.AlterUniqueTogether(
            name='faculty_advisors',
            unique_together={('organisation', 'email')},
        ),
        migrations.RemoveField(
            model_name='faculty_advisors',
            name='organisation_code',
        ),
    ]
