# Generated by Django 4.2.5 on 2023-10-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_certificates_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='faculty_advisor',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
