# Generated by Django 4.2.5 on 2023-10-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_name_faculty_advisors_organisation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faculty_advisors',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='faculty_advisors',
            name='email',
            field=models.CharField(unique=True),
        ),
        migrations.CreateModel(
            name='Faculty_Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('organisation', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Faculty-Org',
                'unique_together': {('organisation', 'email')},
            },
        ),
        migrations.RemoveField(
            model_name='faculty_advisors',
            name='organisation',
        ),
    ]
