# Generated by Django 4.2.5 on 2023-10-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_faculty_advisors_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_org',
            name='password',
        ),
    ]
