# Generated by Django 4.2.5 on 2023-10-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_faculty_org_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_org',
            old_name='email',
            new_name='faculty',
        ),
        migrations.AlterUniqueTogether(
            name='faculty_org',
            unique_together={('organisation', 'faculty')},
        ),
    ]
