# Generated by Django 4.2.5 on 2023-10-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_email_faculty_org_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
