# Generated by Django 4.2.5 on 2023-10-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_org',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculty_advisors', to_field='email'),
        ),
        migrations.AlterField(
            model_name='faculty_org',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users', to_field='email'),
        ),
    ]
