# Generated by Django 4.2.5 on 2023-10-21 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_users_organisation_alter_organisation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField()),
                ('status', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
        migrations.RenameModel(
            old_name='Faculty_Advisors',
            new_name='Faculty_Advisor',
        ),
        migrations.AddField(
            model_name='certificate',
            name='faculty_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.faculty_advisor', to_field='email'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('faculty_advisor', 'serial_no')},
        ),
    ]
