# Generated by Django 4.2.5 on 2023-10-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_certificate_rename_events_event_delete_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='serial_no',
            field=models.CharField(unique=True),
        ),
    ]
