# Generated by Django 4.2.5 on 2023-10-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_certificate_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_org',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculty_advisor'),
        ),
        migrations.AlterField(
            model_name='faculty_org',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation', to_field='name'),
        ),
    ]
