# Generated by Django 4.2.5 on 2023-10-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_faculty_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='faculty_advisor',
            field=models.CharField(),
        ),
    ]
