# Generated by Django 4.2.5 on 2023-11-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_certificate_faculty_advisor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty_Events',
            new_name='Faculty_Event',
        ),
    ]
