# Generated by Django 4.2.5 on 2023-11-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_faculty_event_options_event_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_advisor',
            name='isCDC',
            field=models.BooleanField(default=False),
        ),
    ]
