# Generated by Django 4.2.5 on 2024-01-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_faculty_advisor_iscdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_path',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
