# Generated by Django 4.2.5 on 2024-02-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_certificate_certificate_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_path',
            new_name='cdc_signature',
        ),
        migrations.AddField(
            model_name='certificate',
            name='faculty_signatures',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
