# Generated by Django 4.2.5 on 2024-02-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_certificate_event_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rel_height',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='rel_width',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
    ]
