# Generated by Django 4.2.10 on 2024-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_event_rel_height_event_rel_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='faculties_required',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
