# Generated by Django 4.2.10 on 2024-03-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_organisation_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_advisor',
            name='isDSW',
            field=models.BooleanField(default=False),
        ),
    ]
